import {
  type LucideIcon,
  Baby,
  Bed,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Church,
  CloudSun,
  Coins,
  Compass,
  Cross,
  Crown,
  Dumbbell,
  Flame,
  Globe,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  HouseHeart,
  KeyRound,
  Leaf,
  MoonStar,
  Plane,
  Shield,
  ShieldCheck,
  Sparkles,
  Sunrise,
  Users,
  UserRoundPlus,
  UtensilsCrossed,
} from 'lucide-react';

/** Consistent icon sizing for all prayer cards. */
export const PRAYER_ICON_SIZE = 23;
export const PRAYER_ICON_STROKE = 1.75;

export const prayerIcons: Record<string, LucideIcon> = {
  'Morning Prayer': Sunrise,
  'Night Prayer': MoonStar,
  'Prayer for Healing': HeartPulse,
  'Prayer for Protection': ShieldCheck,
  'Prayer for Strength': Dumbbell,
  'Prayer for Peace': Leaf,
  'Prayer for Family': HouseHeart,
  'Prayer for Children': Baby,
  'Prayer for Breakthrough': KeyRound,
  'Prayer for Guidance': Compass,
  'Prayer for Wisdom': Brain,
  'Prayer for Forgiveness': HandHeart,
  'Prayer for Gratitude': HeartHandshake,
  'Prayer for Hope': Sparkles,
  'Prayer for Faith': Cross,
  'Prayer for Anxiety': CloudSun,
  'Prayer for Financial Blessing': Coins,
  'Prayer for Marriage': Heart,
  'Prayer for Work': BriefcaseBusiness,
  'Prayer for Students': GraduationCap,
  'Prayer for Travel': Plane,
  'Prayer for Sleep': Bed,
  'Prayer for Deliverance': Shield,
  'Prayer for Comfort': Heart,
  'Prayer for Thanksgiving': HeartHandshake,
  'Prayer for Revival': Flame,
  'Prayer for Fasting': UtensilsCrossed,
  'Prayer for Church': Church,
  'Prayer for Nations': Globe,
  'Prayer for Parents': Users,
  'Prayer for Leaders': Crown,
  'Prayer for Friends': UserRoundPlus,
  // Titles in the current prayer library
  'Prayer During Difficult Times': CloudSun,
  'Prayer Before Work': BriefcaseBusiness,
  'Prayer Before Travel': Plane,
  'Prayer for Financial Provision': Coins,
  'Prayer for the Church': Church,
  'Prayer for the Nation': Globe,
  'Prayer for Salvation': Cross,
};

export function getPrayerIcon(title: string): LucideIcon {
  return prayerIcons[title] ?? BookOpen;
}
